# Generated by Django 2.1.2 on 2019-04-28 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authBDF', '0050_auto_20190104_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 15, 55, 12, 332506)),
        ),
    ]
