# Generated by Django 2.1.2 on 2019-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0011_auto_20190104_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='benefit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
